
* 7z split archive
no compression, just copy, volume size 2048m

7zz a -t7z -m0=Copy -v2048m office.7z O365ProPlusRetail.img

* copy drivers, office, font, .ssh dir and registry settings to windows install disk

* Boot to BIOS and erase disk

* Install Windows LTSC

* Disconnect Internet

* In Out-of-Box-Experience create "User" user

* Skip all data collection

* copy .ssh dir to $HOME/

* Windows Defender
disable smart app control

Taskbar. Windows Defender. Apps & Browser Control.  Smart App Control
settings

* import all my registry settings and reboot
import reg file from install disc
 
* on another computer Download drivers from official website
do not use snappy driver installer
fujitsu install u9311 (without m) driver

* Install drivers

* Windows Accessibility
Visual Effects, Disable Animation.  Alway Show scrollbars.
Transparency Effects.

* enable bitlocker without microsoft account
plug in an external drive.  launch control panel applet.

save bitlocker key to external drive.  start encryption

* connect to hotspot
set to metered connection

* scoop
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

scoop install git
scoop bucket add extras
scoop bucket add versions

# install programs
scoop install [list]


* enable ssh agent
# By default, the ssh-agent service is disabled. Configure it to start automatically.
# Run the following command as an administrator.
Get-Service ssh-agent | Set-Service -StartupType Automatic

# Start the service.
Start-Service ssh-agent

# The following command should return a status of Running.
Get-Service ssh-agent

# Load your key files into ssh-agent.
ssh-add

# tell git to use ssh.exe
git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"

* clone git repo
git clone git@github.com:tie-ling/user-win-conf
mv user-win-conf/.git $HOME/
git reset --hard

git clone git@github.com:tie-ling/user-projects $HOME/Projects

* install my own scoop bucket
scoop install $HOME/.config/bucket/

* launch ungoogled chromium
install chrome web store
go to github, search for ublock origin

install ublock origin, disable remote fonts
install noscript
install gopassbridge
install enhanced h264

* import private gpg key
launch kleopatra, import .config/yc-private-key.asc

* backup bitlocker key
right click bitlocker key, use kleopatra to encrypt

save bitlocker key to password repo

* launch emacs (not client)
in order to install packages for the first time

* Install fonts
https://stackoverflow.com/questions/13279014/emacs-bad-font-rendering-under-windows
MUST USE TTF fonts: OTF fonts are badly rendered under windows
otf渲染效果不好。

Libertinus, , noto cjk mono, noto cjk serif

* install office


* activate windows
massgrave.dev

* activate office with kms not Ohook

* limit battery charge to 80%

* launch powerpoint, then login fh-account
do not login the account inside windows settings.

* set login password and pin

* powerpoint language
With your document open:

Press ALT+F11

If you don't see a window labeled "Immediate", press CTRL+G to make it appear.

Type this into the Immediate window then press ENTER:

activepresentation.DefaultLanguageID = msoLanguageIDGerman

* scoop backup
run powershell command
pwsh: (scoop export | ConvertFrom-Json).apps.name
7zip
adb
dark
easyroam-np
emacs
gcc
git
gopass
gopass-jsonapi
gpg4win
hledger
innounp
lessmsi
miktex
nomacs
notepadplusplus
omnissa-horizon-client-np
opentabletdriver
openvpn
polyml
qrencode
rufus
sumatrapdf
ungoogled-chromium
vlc
winscp
xournalpp

* opentabletdriver
inside opentabletdriver, download and enable windows ink plugin
https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk

download and install
https://github.com/X9VoiD/vmulti-bin/releases/

Download the latest release here.
Extract the archive.
Run install_hiddriver.bat as administrator.

* autostart
opentabletdriver
cp 'C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\OpenTabletDriver.lnk' 'C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\OpenTabletDriver.lnk'

fancywm
cp 'C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\FancyWM.lnk' 'C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\'

autohotkey script for fancywm
create shortcut at $home/.config, then copy shortcut to shell:startup

* install icloud for the online drive that i paid for

* claws-mail
use gyuchen86@icloud.com for auto configuration.
but change to guo@wanderian.com later

* disable cpu boost when plugged in
go to eshell, run

powercfg /q to show all normal options
PowerCfg /qh show all hidden plus normal options

run powercfg /l to show profile guid

(hidden settings need to be made visible with registry edits first)

example: powercfg /l
Power Scheme GUID: 381b4222-f694-41f0-9685-ff5bb260df2e Balanced

example powercfg /q
Subgroup GUID: 54533251-82be-4824-96c1-47b60b740d00  (Processor power management)
  Power Setting GUID: be337238-0d82-4146-a960-4f3749d470c7  (Processor performance boost mode)
      Possible Setting Index: 000
      Possible Setting Friendly Name: Disabled

; disable processor boost
powercfg /SETACVALUEINDEX 381b4222-f694-41f0-9685-ff5bb260df2e SUB_PROCESSOR PERFBOOSTMODE 000
powercfg /SETDCVALUEINDEX 381b4222-f694-41f0-9685-ff5bb260df2e SUB_PROCESSOR PERFBOOSTMODE 000

; set minimum cpu to 5%
powercfg  /SETACVALUEINDEX 381b4222-f694-41f0-9685-ff5bb260df2e SUB_PROCESSOR  PROCTHROTTLEMIN 0x00000005
powercfg  /SETDCVALUEINDEX 381b4222-f694-41f0-9685-ff5bb260df2e SUB_PROCESSOR  PROCTHROTTLEMIN 0x00000005

; enable energy saver at all times
powercfg /SETACVALUEINDEX 381b4222-f694-41f0-9685-ff5bb260df2e SUB_ENERGYSAVER ESBATTTHRESHOLD 0x00000064
powercfg /SETDCVALUEINDEX 381b4222-f694-41f0-9685-ff5bb260df2e SUB_ENERGYSAVER ESBATTTHRESHOLD 0x00000064

go to control panel, hardware and sound, power options, edit plan
settings, change advanced power settings
minimum processer state, plugged in: 5%
processor performance boost mode: disabled

go to windows settings, (win+I), go to system, power and battery.  enable battery saver
at all times, for both plugged in and on battery
