
* 7z split archive
no compression, just copy, volume size 2048m

7zz a -t7z -m0=Copy -v2048m office.7z O365ProPlusRetail.img

* copy drivers, office, font and registry settings to windows install disk

* Boot to BIOS and erase disk

* Install Windows LTSC

* Disconnect Internet

* In Out-of-Box-Experience create "User" user

* Skip all data collection

* import all my registry settings and reboot

* Windows Defender
disable smart app control

Taskbar. Windows Defender. Apps & Browser Control.  Smart App Control
settings

 
* on another computer Download drivers from official website
or Snappy Driver Installer
https://www.glenn.delahoy.com/snappy-driver-installer-origin/
remember to disable ipv6 in adapter settings

* Install drivers

* Windows Accessibility
Visual Effects, Disable Animation.  Alway Show scrollbars.
Transparency Effects.

* Install fonts
https://stackoverflow.com/questions/13279014/emacs-bad-font-rendering-under-windows
MUST USE TTF fonts: OTF fonts are badly rendered under windows
otf渲染效果不好。

Libertinus, Iosevka, noto cjk mono, noto cjk serif

* connect to hotspot
set to metered connection

* scoop
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

scoop checkup
enable longpaths support

scoop install git
scoop bucket add extras


* install programs from scoop
# install git first
scoop install git
# enable extras bucket
scoop bucket add extras
# install programs
scoop install [list]

* download and restore .ssh dir
go to github.com/tie-ling/user-win-conf/
copy id_ed25519 raw link

launch powershell
mkdir ~/.ssh
curl -o .ssh/id_ed25519 https://raw.githubusercontent.com

* enable ssh agent
# By default, the ssh-agent service is disabled. Configure it to start automatically.
# Run the following command as an administrator.
Get-Service ssh-agent | Set-Service -StartupType Automatic

# Start the service.
Start-Service ssh-agent

# The following command should return a status of Running.
Get-Service ssh-agent

# Load your key files into ssh-agent.
ssh-add

# tell git to use ssh.exe
git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"

* clone git repo
git clone git@github.com:tie-ling/user-win-conf
mv user-win-conf/.git $HOME/
git reset --hard

git clone git@github.com:tie-ling/user-projects $HOME/Projects

* launch emacs (not client)
in order to install packages for the first time

* launch ungoogled chromium
install ublock origin, disable remote fonts
install noscript
install gopassbridge

* import private gpg key
launch kleopatra, import .config/yc-private-key.asc

* enable bitlocker without microsoft account
plug in an external drive.  launch control panel applet.

save bitlocker key to external drive.  start encryption

right click bitlocker key, use kleopatra to encrypt

save bitlocker key to password repo



* install dnscrypt-proxy as a service
as admin, run cmd and
dnscrypt-proxy -service install

* install office


* activate windows

* activate office with kms not Ohook

* limit battery charge to 80%

* scoop

Installed apps:

Name                      Version                 Source                                                      Updated             Info
----                      -------                 ------                                                      -------             ----
7zip                      26.01                   main                                                        2026-05-03 04:13:05
adb                       37.0.0                  main                                                        2026-05-03 04:18:59
claws-mail                4.4.0-1                 extras                                                      2026-05-05 15:41:10
dark                      3.14.1                  main                                                        2026-05-06 02:07:40
dnscrypt-proxy            2.1.15                  main                                                        2026-05-02 23:25:21
easyroam-np               1.4.7                   C:\Users\User\.config\bucket\easyroam-np.json               2026-05-06 03:52:38
emacs                     30.2                    extras                                                      2026-05-03 04:19:27
fancywm                   2.19.0                  C:\Users\User\.config\bucket\fancywm.json                   2026-05-05 15:35:34
git                       2.54.0                  main                                                        2026-05-03 04:13:24
gopass                    1.16.1                  main                                                        2026-05-03 04:57:32
gopass-jsonapi            1.16.1                  main                                                        2026-05-03 04:59:34
gpg4win                   5.0.2                   extras                                                      2026-05-03 04:57:29
haskell                   9.12.1                  main                                                        2026-05-06 01:47:44
hledger                   1.52.1                  main                                                        2026-05-03 04:19:36
innounp                   2.67.9                  main                                                        2026-05-03 04:19:36
lessmsi                   2.12.9                  main                                                        2026-05-06 02:20:15
nomacs                    3.22.1                  extras                                                      2026-05-03 04:20:06
notepadplusplus           8.9.4                   extras                                                      2026-05-03 04:20:08
omnissa-horizon-client-np 2603-8.18.0-24230927696 C:\Users\User\.config\bucket\omnissa-horizon-client-np.json 2026-05-06 09:12:31
openvpn                   2.7.4-I001              extras                                                      2026-05-06 08:56:06
pdfcpu                    0.12.0                  main                                                        2026-05-03 04:20:22
polyml                    5.9.1                   C:\Users\User\.config\bucket\polyml.json                    2026-05-06 02:38:57
rufus                     4.14                    extras                                                      2026-05-02 21:28:33
sumatrapdf                3.6.1                   extras                                                      2026-05-02 23:50:17
ungoogled-chromium        147.0.7727.116-1.1      extras                                                      2026-05-03 04:20:45
vcredist2022              14.50.35719.0           extras                                                      2026-05-06 02:44:30
vlc                       3.0.23                  extras                                                      2026-05-03 12:19:39
winscp                    6.5.6                   extras                                                      2026-05-03 04:20:48
xournalpp                 1.3.4                   extras                                                      2026-05-03 04:21:10

vlc is more power saving than mpv and mpc-be

* launch powerpoint, then login fh-account
do not login the account inside windows settings.

* set login password and pin

* reenable ipv6 if needed

* change dns server to 127.0.0.1

* maybe install texlive

* powerpoint language
With your document open:

Press ALT+F11

If you don't see a window labeled "Immediate", press CTRL+G to make it appear.

Type this into the Immediate window then press ENTER:

activepresentation.DefaultLanguageID = msoLanguageIDGerman

* scoop backup
$jsonData = scoop export | ConvertFrom-Json

PS C:\Users\User\Desktop> $jsonData.apps.name
7zip
adb
claws-mail
dark
emacs
fancywm
gcc
git
gopass
gopass-jsonapi
gpg4win
hledger
lessmsi
nomacs
notepadplusplus
omnissa-horizon-client-np
opentabletdriver
openvpn
polyml
pwsh
rufus
sumatrapdf
ungoogled-chromium
vcredist2022
vlc
windowsdesktop-runtime-10.0
winscp
xournalpp

* opentabletdriver
inside opentabletdriver, download and enable windows ink plugin
https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk

download and install
https://github.com/X9VoiD/vmulti-bin/releases/

Download the latest release here.
Extract the archive.
Run install_hiddriver.bat as administrator.

autoustart
cp 'C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\OpenTabletDriver.lnk' 'C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\OpenTabletDriver.lnk'
