
* 7z split archive
no compression, just copy, volume size 2048m

7zz a -t7z -m0=Copy -v2048m office.7z O365ProPlusRetail.img

* Boot to BIOS and erase disk

* Install Windows LTSC

* Disconnect Internet

* In Out-of-Box-Experience create "User" user

* Skip all data collection

* Disable Windows Update in Group Policy
run gpedit.msc

Computer Configuration. Administrative Templates. Windows Components
Windows Update. Manage end user experience. Configure Automatic
Updates.  Disabled.


* Windows Defender
disable smart app control

Taskbar. Windows Defender. Apps & Browser Control.  Smart App Control
settings

 
* on another computer Download drivers from official website
or Snappy Driver Installer
https://www.glenn.delahoy.com/snappy-driver-installer-origin/
remember to disable ipv6 in adapter settings

* Install drivers

* Windows Accessibility
Visual Effects, Disable Animation.  Alway Show scrollbars.
Transparency Effects.

* Windows Time & Language
Administrative Language settings

Use UTF-8 for worldwide language support

* touchpad 3-finger click
change to middle button

* Install fonts
https://stackoverflow.com/questions/13279014/emacs-bad-font-rendering-under-windows
MUST USE TTF fonts: OTF fonts are badly rendered under windows
otf渲染效果不好。

Libertinus, Iosevka, noto cjk mono, noto cjk serif

* connect to hotspot
set to metered connection

* scoop
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

scoop checkup
enable longpaths support

scoop install git
scoop bucket add extras


* install programs from scoop
# install git first
scoop install git
# enable extras bucket
scoop bucket add extras
# install programs
scoop install [list]

* download and restore .ssh dir
go to github.com/tie-ling/user-win-conf/
copy id_ed25519 raw link

launch powershell
mkdir ~/.ssh
curl -o .ssh/id_ed25519 https://raw.githubusercontent.com

* enable ssh agent
# By default, the ssh-agent service is disabled. Configure it to start automatically.
# Run the following command as an administrator.
Get-Service ssh-agent | Set-Service -StartupType Automatic

# Start the service.
Start-Service ssh-agent

# The following command should return a status of Running.
Get-Service ssh-agent

# Load your key files into ssh-agent.
ssh-add

# tell git to use ssh.exe
git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"

* clone git repo
git clone git@github.com:tie-ling/user-win-conf
mv user-win-conf/.git $HOME/
git reset --hard

git clone git@github.com:tie-ling/user-projects $HOME/Projects

* install custom keyboard layout registry at $HOME/.config/yc-layout.reg

* launch emacs (not client)

* visit this windows.org file

* windows utc time
reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\TimeZoneInformation" /v RealTimeIsUniversal /d 1 /t REG_DWORD /f


* old context menu
reg.exe add "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve

then reboot

* launch ungoogled chromium
install ublock origin, disable remote fonts
install noscript
install gopassbridge

* import private gpg key
launch kleopatra, import .config/yc-private-key.asc

* enable bitlocker without microsoft account
plug in an external drive.  launch control panel applet.

save bitlocker key to external drive.  start encryption

right click bitlocker key, use kleopatra to encrypt

save bitlocker key to password repo



* install dnscrypt-proxy as a service
as admin, run cmd and
dnscrypt-proxy -service install

* install office


* activate windows

* activate office with kms not Ohook


* scoop

Installed apps:

Name               Version            Source                                    Upd
                                                                                ate
                                                                                d
----               -------            ------                                    ---
7zip               26.01              main                                      202
adb                37.0.0             main                                      202
claws-mail         4.4.0-1            extras                                    202
dnscrypt-proxy     2.1.15             main                                      202
emacs              30.2               extras                                    202
fancywm            2.19.0             C:\Users\User\.config\bucket\fancywm.json 202
git                2.54.0             main                                      202
gopass             1.16.1             main                                      202
gopass-jsonapi     1.16.1             main                                      202
gpg4win            5.0.2              extras                                    202
hledger            1.52.1             main                                      202
nomacs             3.22.1             extras                                    202
notepadplusplus    8.9.4              extras                                    202
openvpn-connect    3.6.0.4074         extras                                    202
pdfcpu             0.12.0             main                                      202
rufus              4.14               extras                                    202
sumatrapdf         3.6.1              extras                                    202
ungoogled-chromium 147.0.7727.137-1.1 extras                                    202
vlc                3.0.23             extras                                    202
winscp             6.5.6              extras                                    202
xournalpp          1.3.4              extras                                    202

vlc is more power saving than mpv and mpc-be

* launch powerpoint, then login fh-account
do not login the account inside windows settings.

* set login password and pin

* reenable ipv6 if needed

* change dns server to 127.0.0.1

* maybe install texlive
